# Generated by Django 5.2.5 on 2026-02-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='is_on_vacation',
            field=models.BooleanField(default=False),
        ),
    ]
